spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: biteNest
  datasource:
    url: jdbc:oracle:thin:@54.180.154.148:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: BITENEST
    password: BITENEST
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  profiles:
    active: local
   
file:
  upload-dir: C:/uploadfiles/
   
   
server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout:
  
  
mybatis:
  configuration:
    jdbc-type-for-null: NULL
  type-aliases-package:
    com.bn.biteNest.recipe.model.vo,
    com.bn.biteNest.recipe.model.dto,
    com.bn.biteNest.recipeComment.model.vo
  mapper-locations: classpath:mapper/*.xml
